<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVROxYyb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVROxYyb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVROxYyb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVROxYyb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVROxYyb\App_KernelDevDebugContainer([
    'container.build_hash' => 'VROxYyb',
    'container.build_id' => 'e324e589',
    'container.build_time' => 1645386039,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVROxYyb');
