<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'app_app_index' => [[], ['_controller' => 'App\\Controller\\AppController::index'], [], [['text', '/']], [], [], []],
    'author_index' => [[], ['_controller' => 'App\\Controller\\AuthorController::index'], [], [['text', '/author/']], [], [], []],
    'author_new' => [[], ['_controller' => 'App\\Controller\\AuthorController::new'], [], [['text', '/author/new']], [], [], []],
    'author_show' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author']], [], [], []],
    'author_edit' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/author']], [], [], []],
    'author_delete' => [['id'], ['_controller' => 'App\\Controller\\AuthorController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/author']], [], [], []],
    'category_index' => [[], ['_controller' => 'App\\Controller\\CategoryController::index'], [], [['text', '/category/']], [], [], []],
    'category_new' => [[], ['_controller' => 'App\\Controller\\CategoryController::new'], [], [['text', '/category/new']], [], [], []],
    'category_show' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], [], []],
    'category_edit' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], [], []],
    'category_delete' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], [], []],
    'comment_index' => [[], ['_controller' => 'App\\Controller\\CommentController::index'], [], [['text', '/comment/']], [], [], []],
    'comment_new' => [[], ['_controller' => 'App\\Controller\\CommentController::new'], [], [['text', '/comment/new']], [], [], []],
    'comment_show' => [['id'], ['_controller' => 'App\\Controller\\CommentController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/comment']], [], [], []],
    'comment_edit' => [['id'], ['_controller' => 'App\\Controller\\CommentController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/comment']], [], [], []],
    'comment_delete' => [['id'], ['_controller' => 'App\\Controller\\CommentController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/comment']], [], [], []],
    'app_post_index' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/admin/post']], [], [], []],
    'app_post_newpost' => [[], ['_controller' => 'App\\Controller\\PostController::newPost'], [], [['text', '/admin/post/newPost']], [], [], []],
    'app_post_editpost' => [['id'], ['_controller' => 'App\\Controller\\PostController::editPost'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/post/editPost']], [], [], []],
    'app_post_deletepost' => [['id'], ['_controller' => 'App\\Controller\\PostController::deletePost'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/post/deletePost']], [], [], []],
    'app_post_showPost' => [['id'], ['_controller' => 'App\\Controller\\PostController::showPost'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/showPost']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
